# Generated by Django 3.1.2 on 2020-11-06 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo', models.CharField(help_text='Nome do grupo. Exemplo: Caixa.', max_length=30, verbose_name='Nome_Grupo')),
                ('descricao', models.TextField(blank=True, help_text='Descricao do grupo. Exemplo: Vendem arroz.', max_length=200, verbose_name='Descricao')),
            ],
        ),
        migrations.CreateModel(
            name='CadastroCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(help_text='Nome fantasia da empresa. Exemplo: Lunar filtros LTDA.', max_length=50, verbose_name='Nome fantasia')),
                ('razao_social', models.CharField(help_text='Razão social da empresa. Exemplo: Judandir Zulu.', max_length=50, verbose_name='Razao social')),
                ('cep', models.IntegerField(help_text='CEP do endereço. Exemplo: 41500-000.', null=True, verbose_name='CEP')),
                ('rua', models.CharField(blank=True, help_text='Nome da rua. Exemplo: 2° Tv 2 de Janeiro.', max_length=60, verbose_name='Rua')),
                ('numero', models.CharField(blank=True, help_text='Numero da residencia', max_length=10, verbose_name='Numero')),
                ('complemento', models.CharField(blank=True, help_text='Complemento de endereço. Exemplo: proximo ao MC donalds.', max_length=60, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, help_text='Nome do bairro. Exemplo: Village.', max_length=20, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, help_text='Nome da cidade. Exemplo:  Salvador.', max_length=20, verbose_name='Cidade')),
                ('codigo_municipal', models.IntegerField(help_text='Codigo municipal. Exemplo: 1200203 (Cruzeiro do Sul).', null=True, verbose_name='Codigo Municipal')),
                ('estado', models.CharField(blank=True, help_text='Estado. Exemplo: Bahia.', max_length=20, verbose_name='Estado')),
                ('pais', models.CharField(blank=True, help_text='Nome do pais. Exemplo: Brasil', max_length=20, verbose_name='Pais')),
                ('tipo_documento', models.CharField(choices=[('PF', 'Pessoa Fisica'), ('PJ', 'Pessoa Juridica')], help_text='Tipo do documento. Exemplo: Pessoa Fisica.', max_length=2, verbose_name='Tipo do documento')),
                ('identidade', models.IntegerField(help_text='Numero da identidade.', null=True, verbose_name='Identidade')),
                ('cnpj', models.IntegerField(help_text='Numero do CNPJ.', null=True, unique=True, verbose_name='CNPJ')),
                ('cpf', models.IntegerField(help_text='Numero do CPF.', null=True, unique=True, verbose_name='CPF')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('EMP', 'Empresa')], help_text='Sexo. Exemplo: M (Masculino).', max_length=3, verbose_name='Sexo')),
                ('inscricao_estadual', models.IntegerField(help_text='Inscrição Estadual.', null=True, unique=True, verbose_name='Inscricao Estadual')),
                ('inscricao_municipal', models.IntegerField(help_text='Inscricao Municipal.', null=True, unique=True, verbose_name='Inscricao Municipal')),
                ('telefone_1', models.IntegerField(help_text='Telefone Fixo 1. Exemplo: Exemplo (11) 1234-5678.', null=True, verbose_name='Primeiro Telefone')),
                ('telefone_2', models.IntegerField(help_text='Telefone Fixo 2. Exemplo (11) 1234-5678.', null=True, verbose_name='Segundo Telefone')),
                ('celular', models.IntegerField(help_text='Celular. Exemplo: (11) 12345-6789.', null=True, verbose_name='Celular')),
                ('email', models.CharField(blank=True, help_text='Email para contato. Exemplo: cliente@dominio.com.br .', max_length=50, verbose_name='Email')),
                ('cnae', models.CharField(blank=True, help_text='Codigo Nacional de Atividade Economica. Exemplo: vendedor de arroz.', max_length=40, verbose_name='CNAE')),
                ('nascimento', models.DateField(help_text='Data de nascimento. Exemplo: 24/04/1994', null=True, verbose_name='Nascimento')),
                ('outras_informacoes', models.TextField(blank=True, help_text='Outras informações. Exemplo: Vende arroz', max_length=100, verbose_name='Outras_informacoes')),
                ('status_cadastro', models.CharField(choices=[('AT', 'Ativo'), ('IT', 'Inativo')], help_text='Status do cadastro do cliente. Exemplo: Ativo', max_length=2, verbose_name='Status_cadastro')),
                ('grupo_cliente', models.ForeignKey(blank=True, default='Sem Grupo', help_text='Grupo em que o cliente pertence.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='CadastroCliente.grupocliente')),
            ],
        ),
    ]
